export const LOAD_LIST_START = 'ADDRESS_BOOK/LOAD_LIST_START';
export const LOAD_LIST_ERROR = 'ADDRESS_BOOK/LOAD_LIST_ERROR';
export const LOAD_LIST_SUCCESS = 'ADDRESS_BOOK/LOAD_LIST_SUCCESS';
export const LOAD_USER_START = 'ADDRESS_BOOK/LOAD_USER_START';
export const LOAD_USER_ERROR = 'ADDRESS_BOOK/LOAD_USER_ERROR';
export const LOAD_USER_SUCCESS = 'ADDRESS_BOOK/LOAD_USER_SUCCESS';
